changesDir: .changes
unreleasedDir: unreleased
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} ({{.Time.Format "January 02, 2006"}})'
kindFormat: '{{.Kind}}:'
changeFormat: '* {{.Body}} [#{{.Custom.Issue}}](https://github.com/hashicorp/terraform-provider-null/issues/{{.Custom.Issue}})'
custom:
- key: Issue
  type: int
  minInt: 1
kinds:
  - label: BREAKING CHANGES
  - label: NOTES
  - label: FEATURES
  - label: IMPROVEMENTS
  - label: BUG FIXES
newlines:
  afterKind: 1
  beforeKind: 1
  endOfVersion: 2

