// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"context"
	"fmt"
	"math/rand"
	"os"
	"strconv"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

func init() {
	seed := time.Now().Unix()

	// If the environment variable TF_NULL_PROVIDER_EXTERNAL_SEED is set, use
	// that as the seed instead of the current time.
	//
	// This is useful for testing, where we want to ensure that the random
	// values generated by this provider are consistent across runs.
	//
	// This environment variable should generally not be used by regular users,
	// and thus does not constitute a stable API.
	const seedEnvVar = "TF_NULL_PROVIDER_EXTERNAL_SEED"
	if externalSeed := os.Getenv(seedEnvVar); externalSeed != "" {
		var err error
		if seed, err = strconv.ParseInt(externalSeed, 10, 64); err != nil {
			panic(fmt.Errorf("cannot parse environment variable %s (%s) as int64: %w", seedEnvVar, externalSeed, err))
		}
	}

	rand.Seed(seed)
}

var _ provider.Provider = (*nullProvider)(nil)

func New() provider.Provider {
	return &nullProvider{}
}

type nullProvider struct{}

func (p *nullProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "null"
}

func (p *nullProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {

}

func (p *nullProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewNullDataSource,
	}
}

func (p *nullProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewNullResource,
	}
}

func (p *nullProvider) Schema(context.Context, provider.SchemaRequest, *provider.SchemaResponse) {
}
