name: compliance

on:
  pull_request:

permissions:
  contents: read

jobs:
  # Reference: ENGSRV-059
  copywrite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: hashicorp/setup-copywrite@3ace06ad72e6ec679ea8572457b17dbc3960b8ce # v1.0.0
      - run: copywrite headers --plan
